server:
  port: 8085

spring:
  application:
    name: notification-service

  mail:
    host: smtp.yandex.ru
    port: 465
    username: missjava@yandex.ru
    password: vzsvwskdvhpnlxan
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
