server:
  port: 8080

spring:
  application:
    name: apigateway

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**, /auth/**

jwt:
  secret: b9CkL2vD7pYhRwT8MfQzNsXpAeVtUcGjQzKlBnTyOp90=
  access-token-expiration: 15m
  refresh-token-expiration: 7d

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG
