server:
  port: 8084

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5434/rental_payment_service
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    admin:
      auto-create: true
    bootstrap-servers: localhost:9092
jwt:
  secret: b9CkL2vD7pYhRwT8MfQzNsXpAeVtUcGjQzKlBnTyOp90=
  lifetimeMinutes: 15
  refreshExpirationDays: 7

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
