server:
  port: 8082

spring:
  application:
    name: car-service

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5434/rental_car_service
    username: postgres
    password: postgres

  flyway:
    enabled: true

  kafka:
    admin:
      auto-create: true
    bootstrap-servers: localhost:9092

jwt:
  secret: b9CkL2vD7pYhRwT8MfQzNsXpAeVtUcGjQzKlBnTyOp90=
  lifetimeMinutes: 15
  refreshExpirationDays: 7