server:
  port: 8082

spring:
  application:
    name: car-service

  springdoc:
    swagger-ui:
      enabled: true
      path: /swagger-ui.html

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5434/rental_car_service
    username: postgres
    password: postgres

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: car-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.common

jwt:
  secret: b9CkL2vD7pYhRwT8MfQzNsXpAeVtUcGjQzKlBnTyOp90=
  lifetimeMinutes: 15
  refreshExpirationDays: 7