server:
  port: 8084

spring:
  application:
    name: user-service

  springdoc:
    swagger-ui:
      enabled: true
      path: /swagger-ui.html

  jwt:
    secret: b9CkL2vD7pYhRwT8MfQzNsXpAeVtUcGjQzKlBnTyOp90=
    lifetimeMinutes: 15
    refreshExpirationDays: 7

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5434/rental_user_service
    username: postgres
    password: postgres

  flyway:
    enabled: true