DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'role') THEN
        CREATE TYPE role AS ENUM ('ADMIN', 'USER');
    END IF;
END $$;

ALTER TABLE users
ADD COLUMN user_role role NOT NULL DEFAULT 'USER';

ALTER TABLE users
ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
